### ISSUE TITLE
hello,wanna ask there have inference code?

### ISSUE THREAD

**Issue by gyftsy** [xuehuachunsheng/LLNet-tf#6]
dear:
may i ask :there is inference code or not?using your code ,i have got weight.but i cant test the pic.so wanna ask this qa

**Comment by xuehuachunsheng** [comment]
Dear,
    This is my all code, and now I feel sorry because I dont prepare to improve this code.  The inference code is not difficult and I'm sure you can do it.

> dear:
> may i ask :there is inference code or not?using your code ,i have got weight.but i cant test the pic.so wanna ask this qa
